insert into products (name, description, price) values ('Movies', 'Beef - Flank Steak', 55.5);
insert into products (name, description, price) values ('Grocery', 'Pernod', 353.56);
insert into products (name, description, price) values ('Computers', 'Truffle Shells - Semi - Sweet', 195.14);
insert into products (name, description, price) values ('Garden', 'Wine - Sogrape Mateus Rose', 498.86);
insert into products (name, description, price) values ('Baby', 'Apples - Sliced / Wedge', 981.62);
insert into products (name, description, price) values ('Toys', 'Pepper - Paprika, Hungarian', 415.2);
insert into products (name, description, price) values ('Clothing', 'Cheese - Mozzarella', 11.9);
insert into products (name, description, price) values ('Computers', 'Coconut - Shredded, Sweet', 872.47);
insert into products (name, description, price) values ('Computers', 'Garbage Bag - Clear', 282.63);
insert into products (name, description, price) values ('Grocery', 'Towel - Roll White', 918.37);
insert into products (name, description, price) values ('Books', 'Olives - Black, Pitted', 6.94);
insert into products (name, description, price) values ('Games', 'Rhubarb', 103.45);
insert into products (name, description, price) values ('Computers', 'Table Cloth 144x90 White', 816.58);
insert into products (name, description, price) values ('Baby', 'Bread Roll Foccacia', 848.07);
insert into products (name, description, price) values ('Kids', 'Tea - Lemon Scented', 34.81);
insert into products (name, description, price) values ('Sports', 'Creme De Banane - Marie', 225.74);
insert into products (name, description, price) values ('Books', 'Thyme - Dried', 645.6);
insert into products (name, description, price) values ('Garden', 'Duck - Fat', 116.46);
insert into products (name, description, price) values ('Electronics', 'Chicken - Base', 993.41);
insert into products (name, description, price) values ('Computers', 'Pastry - Baked Cinnamon Stick', 26.91);
insert into products (name, description, price) values ('Sports', 'Sugar - Invert', 244.33);
insert into products (name, description, price) values ('Computers', 'Mcguinness - Blue Curacao', 931.97);
insert into products (name, description, price) values ('Garden', 'Beef - Rib Roast, Cap On', 211.82);
insert into products (name, description, price) values ('Kids', 'Calaloo', 486.39);
insert into products (name, description, price) values ('Clothing', 'Lamb - Whole, Fresh', 139.64);
insert into products (name, description, price) values ('Books', 'Lettuce - Boston Bib - Organic', 686.03);
insert into products (name, description, price) values ('Beauty', 'Liqueur - Melon', 786.8);
insert into products (name, description, price) values ('Games', 'Carbonated Water - Peach', 959.62);
insert into products (name, description, price) values ('Baby', 'Coffee - Cafe Moreno', 838.82);
insert into products (name, description, price) values ('Beauty', 'Chocolate - White', 274.58);
insert into products (name, description, price) values ('Books', 'Pork Loin Cutlets', 630.53);
insert into products (name, description, price) values ('Outdoors', 'Squid - Tubes / Tenticles 10/20', 703.03);
insert into products (name, description, price) values ('Garden', 'Pears - Bosc', 704.8);
insert into products (name, description, price) values ('Garden', 'Capers - Pickled', 139.08);
insert into products (name, description, price) values ('Music', 'Salmon - Atlantic, Fresh, Whole', 630.47);
insert into products (name, description, price) values ('Computers', 'Rhubarb', 542.93);
insert into products (name, description, price) values ('Clothing', 'Yucca', 728.36);
insert into products (name, description, price) values ('Clothing', 'Bread - Multigrain, Loaf', 393.67);
insert into products (name, description, price) values ('Automotive', 'Pork - Chop, Frenched', 594.89);
insert into products (name, description, price) values ('Baby', 'Smoked Paprika', 76.74);
insert into products (name, description, price) values ('Grocery', 'Lamb - Shoulder', 602.56);
insert into products (name, description, price) values ('Games', 'Chicken - Soup Base', 896.69);
insert into products (name, description, price) values ('Games', 'Soup - Campbells, Beef Barley', 913.2);
insert into products (name, description, price) values ('Outdoors', 'Ice Cream - Strawberry', 722.2);
insert into products (name, description, price) values ('Shoes', 'Crab - Claws, 26 - 30', 39.41);
insert into products (name, description, price) values ('Sports', 'Cheese - Boursin, Garlic / Herbs', 833.39);
insert into products (name, description, price) values ('Clothing', 'Pickerel - Fillets', 207.0);
insert into products (name, description, price) values ('Jewelery', 'Vegetable - Base', 460.17);
insert into products (name, description, price) values ('Baby', 'Gatorade - Orange', 889.95);
insert into products (name, description, price) values ('Sports', 'Veal - Inside, Choice', 234.69);
insert into products (name, description, price) values ('Kids', 'Thermometer Digital', 712.17);
insert into products (name, description, price) values ('Tools', 'Veal - Liver', 686.31);
insert into products (name, description, price) values ('Music', 'Nut - Peanut, Roasted', 445.53);
insert into products (name, description, price) values ('Kids', 'Cookies - Englishbay Wht', 51.01);
insert into products (name, description, price) values ('Clothing', 'Soup - Campbells Beef Noodle', 343.57);
insert into products (name, description, price) values ('Beauty', 'Nut - Pecan, Halves', 724.62);
insert into products (name, description, price) values ('Computers', 'Chocolate Bar - Oh Henry', 64.46);
insert into products (name, description, price) values ('Tools', 'Rice - Basmati', 255.74);
insert into products (name, description, price) values ('Beauty', 'Yukon Jack', 928.86);
insert into products (name, description, price) values ('Toys', 'Coffee - Espresso', 180.51);
insert into products (name, description, price) values ('Home', 'Mushroom - Porcini Frozen', 671.04);
insert into products (name, description, price) values ('Computers', 'Wine - Red, Marechal Foch', 947.99);
insert into products (name, description, price) values ('Grocery', 'Veal - Knuckle', 57.19);
insert into products (name, description, price) values ('Industrial', 'Apple - Macintosh', 91.22);
insert into products (name, description, price) values ('Grocery', 'Soup - Tomato Mush. Florentine', 791.47);
insert into products (name, description, price) values ('Home', 'Bread - Roll, Whole Wheat', 186.23);
insert into products (name, description, price) values ('Tools', 'Cranberries - Frozen', 538.33);
insert into products (name, description, price) values ('Baby', 'Cheese - Mix', 794.67);
insert into products (name, description, price) values ('Baby', 'Apple - Royal Gala', 747.72);
insert into products (name, description, price) values ('Computers', 'Coriander - Ground', 354.27);
insert into products (name, description, price) values ('Books', 'Cloves - Whole', 878.19);
insert into products (name, description, price) values ('Music', 'Onions - Red Pearl', 666.7);
insert into products (name, description, price) values ('Movies', 'Wine - Magnotta, White', 945.29);
insert into products (name, description, price) values ('Jewelery', 'Pesto - Primerba, Paste', 680.24);
insert into products (name, description, price) values ('Games', 'Bar - Granola Trail Mix Fruit Nut', 553.74);
insert into products (name, description, price) values ('Home', 'Plasticknivesblack', 506.63);
insert into products (name, description, price) values ('Garden', 'Yukon Jack', 892.96);
insert into products (name, description, price) values ('Sports', 'Melon - Watermelon Yellow', 154.67);
insert into products (name, description, price) values ('Clothing', 'Tea Leaves - Oolong', 466.12);
insert into products (name, description, price) values ('Movies', 'Roe - Lump Fish, Black', 813.99);
insert into products (name, description, price) values ('Baby', 'Sauce - Sesame Thai Dressing', 234.76);
insert into products (name, description, price) values ('Shoes', 'Beef - Ground Medium', 628.68);
insert into products (name, description, price) values ('Beauty', 'Molasses - Fancy', 702.29);
insert into products (name, description, price) values ('Games', 'Cup - 4oz Translucent', 641.37);
insert into products (name, description, price) values ('Books', 'Cookie Trail Mix', 333.4);
insert into products (name, description, price) values ('Baby', 'Parasol Pick Stir Stick', 909.06);
insert into products (name, description, price) values ('Jewelery', 'Ecolab - Hand Soap Form Antibac', 869.28);
insert into products (name, description, price) values ('Outdoors', 'Wine - Barossa Valley Estate', 964.3);
insert into products (name, description, price) values ('Jewelery', 'Beef Wellington', 798.5);
insert into products (name, description, price) values ('Home', 'Limes', 539.47);
insert into products (name, description, price) values ('Outdoors', 'Wine - Jaboulet Cotes Du Rhone', 247.73);
insert into products (name, description, price) values ('Tools', 'Schnappes - Peach, Walkers', 52.14);
insert into products (name, description, price) values ('Garden', 'Rabbit - Saddles', 428.23);
insert into products (name, description, price) values ('Movies', 'Mini - Vol Au Vents', 99.29);
insert into products (name, description, price) values ('Jewelery', 'Bagel - Everything Presliced', 595.03);
insert into products (name, description, price) values ('Industrial', 'Tobasco Sauce', 348.49);
insert into products (name, description, price) values ('Beauty', 'Bread - Roll, Whole Wheat', 611.51);
insert into products (name, description, price) values ('Health', 'Ham - Proscuitto', 404.77);
insert into products (name, description, price) values ('Clothing', 'Wine - Magnotta - Pinot Gris Sr', 723.54);
insert into products (name, description, price) values ('Baby', 'Flour - Whole Wheat', 658.93);